apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # Mejor para Minikube
  selector:
    io.kompose.service: frontend
  ports:
    - port: 4200         # Puerto accesible desde el exterior
      targetPort: 80     # Puerto donde escucha tu contenedor
      nodePort: 30172    # Opcional. Si lo omites, Kubernetes asigna uno aleatorio
